create table PROJECT353.SUBMISSIONS
(
	
	SUBMISSION_ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
        USER_ID VARCHAR(15),
	RATING DOUBLE,
	SUBMISSION_DATE DATE default CURRENT DATE,
	SUBMISSION_CONTENT BLOB(2147483647),
        CONSTRAINT submissions_submission_id_pk PRIMARY KEY(SUBMISSION_ID)
);


INSERT INTO PROJECT353.SUBMISSIONS(USER_ID, RATING, SUBMISSION_CONTENT)
VALUES('doluwan',5.0,NULL);